language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install .
before_script:
  - pip install --quiet black coverage six python-coveralls
  - black --check .
script: coverage run --branch --source fqdn -m py.test
after_success:
  - coverage report
  - coveralls
