language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install .
before_script:
  - pip install --quiet coverage six python-coveralls
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then pip install black && black --check .; fi
script: coverage run --branch --source fqdn -m py.test
after_success:
  - coverage report
  - coveralls
